Add kubernetes wrapper docs
zalando/zmon-docs pull request #67
Opened 2017-03-22 16:54 UTC by mohabusama

Docs for https://github.com/zalando-zmon/zmon-worker/pull/214

2017-03-27 07:20 UTC, hjacobs commented
Do we really need function aliases like `rs` for replica sets? I would remove these (in the code of course)...

2017-03-27 11:44 UTC, mohabusama commented
I thought this would be easier and less error prone (``cm`` vs ``configmaps`` ,`` pv`` vs ``persistentvolumes``), It is also aligned with Kubernetes aliases.

2017-03-27 13:28 UTC, hjacobs commented
@mohabusama yes, but reading something like `kubernetes().rs()` in a ZMON check definition looks weird and is hard to understand (for people not knowing Kubernetes details).

2017-03-28 09:43 UTC, mohabusama commented
I assumed people using Kubernetes wrapper are already familiar with Kubernetes ;)

I will remove it if you find it confusing :)

2017-03-28 10:11 UTC, hjacobs commented
I would remove all short versions/aliases as this is confusing and somebody else (not familiar with Kubernetes) might read the check (e.g. in 24x7 incident case).

2017-03-29 10:48 UTC, mohabusama commented
👍

2017-03-29 12:26 UTC, lmineiro requested changes

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +    Kubernetes wrapper will authenticate using service account, which assumes the wroker is running in a Kubernetes cluster.
s/wroker/worker

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +The following examples show different usage of Kubernetes wrapper with label filtering:
"of the Kubernetes wrapper"

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +    Kubernetes wrapper will authenticate using service account, which assumes the wroker is running in a Kubernetes cluster.
Let's add a short statement clearly saying that all the following functions of the wrapper are scoped to the k8s cluster that the zmon worker belongs to.

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        :param ready: Pod ready status. If None then all pods are returned.
"Pod Readiness status. If None then all podsare returned"

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of nodes. Namespace is ignored.
"Namespace doesn't apply"

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of Services.
Add link to https://kubernetes.io/docs/user-guide/services/

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of Pods.
Link to https://kubernetes.io/docs/user-guide/pods/

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of nodes. Namespace is ignored.
Add link to https://kubernetes.io/docs/admin/node/

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of Ingresses.
Add link to https://kubernetes.io/docs/user-guide/ingress/

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of Statefulsets.
Add link to https://kubernetes.io/docs/user-guide/petset/ (or statefulset if they re-fix-f*ck-it-up)

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of ReplicaSets.
Add link to https://kubernetes.io/docs/user-guide/replicasets/

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of Deployments.
Add link to https://kubernetes.io/docs/user-guide/deployments/

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of ConfigMaps.
Add link to https://kubernetes.io/docs/user-guide/configmap/

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        :return: List of ConfigMaps. Typical ConfigMap has "metadata", "status" and "spec".
Couldn't find "spec" in the basic example from k8s docs

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of PersistentVolumes.
Add link to https://kubernetes.io/docs/user-guide/persistent-volumes/

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        :return: List of PersistentVolumes. Typical PersistentVolume has "metadata", "status" and "spec".
Couldn't find "status" in https://kubernetes.io/docs/user-guide/persistent-volumes/ basic example

2017-03-29 12:26 UTC, lmineiro commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        Return list of PersistentVolumeClaims.
Add link to https://kubernetes.io/docs/user-guide/persistent-volumes/ (Couldn't find any better link)

2017-03-29 12:55 UTC, mohabusama commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        :return: List of PersistentVolumes. Typical PersistentVolume has "metadata", "status" and "spec".
It is definitely returned by the API

```python
In [1]: pv.obj.keys()
Out[1]: dict_keys(['spec', 'status', 'metadata'])
```

``$ kubectl get pv pvc-1cca9cf3-... -o yaml``

```yaml
...
status:
  phase: Bound
```

2017-03-29 13:07 UTC, mohabusama commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        :return: List of ConfigMaps. Typical ConfigMap has "metadata", "status" and "spec".
Nice catch! only ``metadata`` and ``data`` are returned.

2017-03-29 13:14 UTC, mohabusama commented on docs/user/check-ref/kubernetes_wrapper.rst
> +    Kubernetes wrapper will authenticate using service account, which assumes the wroker is running in a Kubernetes cluster.
Done

2017-03-29 13:14 UTC, mohabusama commented on docs/user/check-ref/kubernetes_wrapper.rst
> +The following examples show different usage of Kubernetes wrapper with label filtering:
Done

2017-03-29 13:14 UTC, mohabusama commented on docs/user/check-ref/kubernetes_wrapper.rst
> +        :param ready: Pod ready status. If None then all pods are returned.
Done

2017-03-29 13:15 UTC, mohabusama commented
@lmineiro all links have been added.

2017-03-29 13:20 UTC, lmineiro commented
👍

2017-03-29 13:26 UTC, mohabusama commented
👍

2017-03-29 13:26 UTC, merged